[package]
name = "blossom"
version = "0.1.0"
authors = ["Magnus Nybråten Malmquist <magnusnym97@gmail.com>"]
edition = "2021"
license = "MIT"

description = "A Rust Bloom filter implementation."

Topics
Resources

[dependencies]
